version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "8014:8014"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:utec@52.206.143.132:8005/dbCliente
      - FLASK_ENV=development
