version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_BASE_URL=http://PROY-TLS-f20e4defd215dfd4.elb.us-east-1.amazonaws.com
      - AUTH_SERVICE_URL=http://PROY-TLS-f20e4defd215dfd4.elb.us-east-1.amazonaws.com:5000
      - CLIENT_SERVICE_URL=http://PROY-TLS-f20e4defd215dfd4.elb.us-east-1.amazonaws.com:8014
      - MED_SERVICE_URL=http://PROY-TLS-f20e4defd215dfd4.elb.us-east-1.amazonaws.com:8016
    volumes:
      - .:/app
