# Usar una imagen base oficial de Python
FROM python:3.9

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de requerimientos y el código de la aplicación
COPY requirements.txt requirements.txt
COPY . .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto en el que correrá la aplicación Flask
EXPOSE 8014

# Comando para correr la aplicación
CMD ["python", "cita.py"]
