version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      FLASK_ENV: development
      DATABASE_URI: "mysql+pymysql://testuser:testpassword@db/testdb"
    ports:
      - "8014:8014"
    depends_on:
      - db

volumes:
  db_data:
